# Generated by Django 2.2.2 on 2022-09-13 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20220913_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 12, 49, 12, 310603)),
        ),
    ]
