# Generated by Django 2.2.2 on 2022-09-13 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20220913_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 13, 5, 17, 744721)),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='My title', max_length=50),
        ),
    ]
